### PR TITLE
Setup authorization data for API requests

### PR DESCRIPTION
**Pull request by bboozzoo**
Add authorization data to outgoing API requests. The series add an `ApiClient` helper with a convenience method `Request()` for creating request wrappers. Request wrapper `ApiRequest` implements `ApiRequester` interface and automatically append authorization data to the outgoing request if none is present.

Mender controller has been updated to cache authorization code so that we don't waste time/cycles for reloading it each time it's needed.

@pasinskim @kacf

### CODE REVIEW

**Comment by kacf** [comment]
Good stuff!

One question: Could we stick to calling it `authToken` throughout, instead of `authCode`? I find it's easier to understand the intention of the variable "token" than "code" (unless, *I'm* the one that's confused, and `authCode` is not the token :-) ).

**Comment by bboozzoo** [comment]
I don't have any strong opinion here, `authToken` is fine. IDo you want to rename `AuthCode` type alias to `AuthToken` too?

**Comment by kacf** [comment]
Yes, let's use the same terminology everywhere.

**Comment by kacf** [comment]
> rename AuthToken to AuthCode

I think you're doing the opposite. :-)

**Comment by bboozzoo** [comment]
On Fri, Jul 1, 2016 at 10:53 AM, Kristian Amlie <notifications@github.com>
wrote:

> rename AuthToken to AuthCode
>
> I think you're doing the opposite. :-)
>

oops, right ;)

**Pull request merged**
