### PR TITLE
Fix the readme to reflect the client binary name change.

### PR DESCRIPTION
**Pull request by pasinskim**
Changelog: title

Signed-off-by: Marcin Pasinski <marcin.pasinski@northern.tech>

### CODE REVIEW

**Review by kacf — APPROVED** [review]
Aha!

**Comment by kacf** [comment]
@pasinskim: You need to rebase, your version is almost two years old! :-)

**Comment by kacf** [comment]
But I checked, the fix is still valid.

**Comment by pasinskim** [comment]
@kacf yeah, it's been a while... Should be fixed now!

**Review by lluiscampos — CHANGES_REQUESTED** [review]
I don't think this honors a Changelog entry, though. Can you please set it to `None`? Sorry I didn't catch this before

**Comment by pasinskim** [comment]
@lluiscampos thanks. Fixed!

**Comment by lluiscampos** [comment]
> @lluiscampos thanks. Fixed!
@pasinskim  Sorry, but `Name` is not a valid tag... ;)

**Comment by oleorhagen** [comment]
@pasinskim ping

**Comment by pasinskim** [comment]
> > @lluiscampos thanks. Fixed!
> 
> @pasinskim Sorry, but `Name` is not a valid tag... ;)

How hard it can be :) We should be all good now!

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
