### PR TITLE
test: Verify that identity is marshaled the same way as in Go

### PR DESCRIPTION
**Pull request by oleorhagen**
This adds a test to verify that identity is marshaled in the same way as it is
in the Golang client code.

See the test here:
`https://github.com/mendersoftware/mender/blob/mendersoftware/device/identity_data_test.go#L130`

Note that we still might have a UTF-8 issue here. But this is a separate topic.

Ticket: MEN-6825

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

-------

### CODE REVIEW

**Comment by kacf** [comment]
I assume these are passing because all the operations involved in this particular test case are in fact using auto-conversion. So which ones aren't using it? Database? HTTP requests maybe?

**Comment by oleorhagen** [comment]
> I assume these are passing because all the operations involved in this particular test case are in fact using auto-conversion. So which ones aren't using it? Database? HTTP requests maybe?

I assumed they we're passing, at least that is the case for me locally, because my `locale` is `UTF-8`

**Comment by kacf** [comment]
But that should also break, in theory, because the database is not doing conversion to UTF-8, AFAIK. OTOH, it possible that nothing will break as long as the locale on the system doesn't change, since even if you introduce inconsistencies, they don't become visible until you change the locale. I think we need to hunt specifically for a failing case.

**Comment by lluiscampos** [comment]
Nit: the link in the commit message (https://github.com/mendersoftware/mender/blob/mendersoftware/device/identity_data_test.go#L130) will disappear after we merge the feature branch. Use a link for an specific master commit instead

**Comment by oleorhagen** [comment]
> But that should also break, in theory, because the database is not doing conversion to UTF-8, AFAIK. OTOH, it possible that nothing will break as long as the locale on the system doesn't change, since even if you introduce inconsistencies, they don't become visible until you change the locale. I think we need to hunt specifically for a failing case.

Yes, but I feel we are discussing something else than this PR now. I maybe should/could/can keep the UTF-8 out of this. It was originally just meant to verify that we marshal the JSON in the same way (disregarding the UTF-8/string issues [if there are any])

**Comment by kacf** [comment]
Hmm, maybe you're right. To be honest it's hard to wrap my head around this.

But do you agree that we should try to deliberately find a failing scenario, just to verify that this is in fact a problem? It might involve setting your own locale to something weird, but it's for testing purposes.

**Comment by oleorhagen** [comment]
> Hmm, maybe you're right. To be honest it's hard to wrap my head around this.
> 
> But do you agree that we should try to deliberately find a failing scenario, just to verify that this is in fact a problem? It might involve setting your own locale to something weird, but it's for testing purposes.

Yes, absolutely!

I will link to this conversation in the string representation research ticket

**Review by kacf — APPROVED** [review]
Good! Then I request that you leave the Unicode tests out of this PR, because I'm still not convinced that they would reveal the problem the way we want, so it's better not to submit them while we are still unsure.

**Comment by oleorhagen** [comment]
> Good! Then I request that you leave the Unicode tests out of this PR, because I'm still not convinced that they would reveal the problem the way we want, so it's better not to submit them while we are still unsure.

:apple: :orange_circle:

**Pull request merged**
