### PR TITLE
[pipeline] Add trigger to integration to build/publish addons image

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Review by tranchitella — APPROVED** [review]

**Review by mzedel — APPROVED** [review]

**Comment by mzedel** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
@mzedel This PR cannot possibly affect `mender-qa` pipeline, so I was no planning on running it.

**Comment by mzedel** [comment]
@lluiscampos fyi: the pipeline run was supposed to make the checks happy and potentially unblock the failed `-addons` image update

**Comment by lluiscampos** [comment]
> @lluiscampos fyi: the pipeline run was supposed to make the checks happy and potentially unblock the failed `-addons` image update

@mzedel  The mender-qa pipeline is expensive for just "making CI happy" when we are absolutely certain that no code change affects the pipeline. In this cases is well justified to use the admin rights to merge a PR. Note that I always wait for the individual pipeline (integration repo, in this case)

With regards to the `-addons` image. This image is published from integration repo, not from mender-qa

**Comment by mzedel** [comment]
sure, but considering this pipeline being run at night and no one with admin rights around, the PR title clearly states that the intention is to build/publish the addons image + IMO the expensive part in this situation is the delay due to a developer being blocked...

**Comment by lluiscampos** [comment]
That is a good point that I'll take into account next time. I did this on a Saturday and didn't expect anyone reviewing it on a Sunday :)

**Pull request merged**
