### PR TITLE
Update README.md to Mender Hub, and add bugtracker to avoid use of Github issues

### PR DESCRIPTION
**Pull request by estenberg**
Quick review requested. :)

If ok I will update all repos.

### CODE REVIEW

**Comment by lluiscampos** [comment]
There is already PR #359 with similar changes. @michaelatmender Which one should we merge?

**Comment by mirzak** [comment]
Note that #359 also adds IRC channel to the list of ways to contact us which we might as well do while at it.

**Comment by kacf** [comment]
I resolved the conflict and kept all of the relevant sections.

**Comment by estenberg** [comment]
Nice, thanks - I wasn't aware of that other PR.

Are someone planning to merge this change into all the other repos' README.md?

**Comment by mirzak** [comment]
You said you are :)

**Comment by estenberg** [comment]
Just wanted to make sure there were no other PRs / plans I didn't know about.
Will do!

**Comment by estenberg** [comment]
All README.md updated! No challenge for a beautiful bash script.

**Pull request merged**
