### PR TITLE
Replace the current progressbar with mendersoftware/progressbar

### PR DESCRIPTION
**Pull request by oleorhagen**
This leads to a lot less verbose output. So no more:

```
............................ 1024 KB
............................ 1024 KB
```

And more:
```
..................................... - 100 %
```

Mender-master:
```
go build -ldflags "-X github.com/mendersoftware/mender/conf.Version=483c605"  
➜ mender git:(483c605) ✗ strip mender
➜ mender git:(483c605) ✗ ls -lh mender
-rwxr-xr-x 1 olepor olepor 7,6M nov.  12 18:36 mender
```

Mender minimal progressbar:
```
➜ mender git:(minimalprogressbar) ✗ strip mender
➜ mender git:(minimalprogressbar) ✗ ls -lh mender
-rwxrwxr-x 1 olepor olepor 7,6M nov.  12 18:36 mender
```

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
The user code looks clean. I also had a look at the `progressbar` library and couldn't spot any errors. Nice initiative :100: 

As you well know, you need a PR on `meta-mender` for the license change.

Side note: this requires yet another Debian package. I will start packaging it ASAP so that we don't block the next release (as has happened with the `openssl` one).

**Comment by oleorhagen** [comment]
> The user code looks clean. I also had a look at the `progressbar` library and couldn't spot any errors. Nice initiative 100
> 
> As you well know, you need a PR on `meta-mender` for the license change.
Yes, this I do know :) Just wanted eyes on it.
> 
> Side note: this requires yet another Debian package. I will start packaging it ASAP so that we don't block the next release (as has happened with the `openssl` one).

This I did not realize! Thank you, and I'm sorry if this is causing you disruption in this sprint. There is no rush here. I just wanted eyes and consensus on this.

And part of it was to ask for eyes on the progressbar library also. It has not had any reviews on it so far.

**Comment by lluiscampos** [comment]
> > Side note: this requires yet another Debian package. I will start packaging it ASAP so that we don't block the next release (as has happened with the `openssl` one).
> 
> This I did not realize! Thank you, and I'm sorry if this is causing you disruption in this sprint. There is no rush here. I just wanted eyes and consensus on this.

Don't worry. I can take it next sprint reserving some capacity for it. But the important bit is to give visibility to this detail: Debian will not use gomod nor vendored, so we need to provide additional packages.

**Comment by oleorhagen** [comment]
https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/215741512

**Comment by kacf** [comment]
:+1:

**Comment by ankit2002** [comment]
Hello, Is it possible to have this feature as a configuration options. Or is it still possible to get the old verbose logs, with the new mender release. Thanks

**Comment by kacf** [comment]
It is not possible I'm afraid.

Note that the whole client is in the process of being [rewritten and replaced](https://hub.mender.io/t/mender-to-rewrite-client-using-c-and-retain-go-for-its-backend/5332). It will remain compatible with existing devices, but things like logging is probably going to change significantly.

**Pull request merged**
