### PR TITLE
Send inventory with different interval than update request. 

### PR DESCRIPTION
**Pull request by pasinskim**

### CODE REVIEW

**Comment by pasinskim** [comment]
Merge together with https://github.com/mendersoftware/meta-mender/pull/188

**Comment by kacf** [comment]
Is this basically a simpler and less generic version of #157?

**Comment by pasinskim** [comment]
@kacf that's right. Let's decide which one do we want.

**Comment by kacf** [comment]
Maybe we should go with this one for now. #157 has potential, but it needs some more work, and isn't strictly necessary right now.

**Pull request merged**
