### PR TITLE
reboot device Update Module

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
I think we should not put this in the main repository, because we know that this is a hacky method, and we would rather implement this in a different way. What we would like is to enable [persistent connections](https://drive.google.com/file/d/15ZyLIB3W5QFWONNEVhmOppUyTNE4dGst/view?usp=sharing) and then adding actionable API that can reboot without going through an update. This could also be used to log in via SSH, without having an open port 22, for example. So I suggest this is added on Mender Hub instead, as a more temporary community hack.

**Comment by merlin-northern** [comment]
> I think we should not put this in the main repository, because we know that this is a hacky method, and we would rather implement this in a different way. What we would like is to enable [persistent connections](https://drive.google.com/file/d/15ZyLIB3W5QFWONNEVhmOppUyTNE4dGst/view?usp=sharing) and then adding actionable API that can reboot without going through an update. This could also be used to log in via SSH, without having an open port 22, for example. So I suggest this is added on Mender Hub instead, as a more temporary community hack.

sure will do, let me wait for the support case this was created for, and them I will move it.

**Comment by drewmoseley** [comment]
@merlin-northern  we do have https://github.com/mendersoftware/mender-update-modules which would be a good place for this.

**Comment by merlin-northern** [comment]
thanks. closing. moved to https://github.com/mendersoftware/mender-update-modules/pull/17

**Pull request closed without merging**
