### PR TITLE
Upgrade openssl dependency.

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
Pipelines running for this (may be updated as I try more builds):

* Dunfell: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/512216989
* Kirkstone: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/512213675

**Review by oleorhagen — COMMENTED** [review]
Why this, and not a released version?

**Comment by oleorhagen** [comment]
nvm, I seen the ur PR to the repo now. Are we going to upstream it?

**Comment by kacf** [comment]
The upstream repo is dead. There are untouched pull requests there from several years ago, including from us.

**Review by oleorhagen — APPROVED** [review]

**Comment by kacf** [comment]
The status looks bad because this is mixed with the kirkstone build, but it passed for dunfell [here](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/562127840).

**Pull request merged**
