### PR TITLE
Bottom?

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: None

Signed-off-by: Ole Petter <ole.orhagen@cfengine.com>

### CODE REVIEW

**Comment by olehermanse** [comment]
@mender-bottom jenkins

**Comment by olehermanse** [comment]
@mender-bottom jenkins!

**Comment by mender-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://mender-jenkins.mender.io//job/mender-builder/844/)

https://mender-jenkins.mender.io/job/mender-builder/844/

**Comment by mender-bottom** [comment]
Sure, I triggered a build:

[Build Status](https://mender-jenkins.mender.io//job/mender-builder/846/)

https://mender-jenkins.mender.io/job/mender-builder/846/

**Pull request closed without merging**
