### PR TITLE
removed dead code and unsed variables, updated .travis.yml

### PR DESCRIPTION
**Pull request by GregorioDiStefano**
Signed-off-by: Greg Di Stefano <greg.distefano+github@gmail.com>

### CODE REVIEW

**Comment by kacf** [comment]
It found more dead code. :-)

**Comment by bboozzoo** [comment]
@GregorioDiStefano can you split the commit in two? .travis.yml change is unrelated to removal of dead code.

**Comment by GregorioDiStefano** [comment]
the .travis.yml update adds the actual checking for dead code

**Comment by bboozzoo** [comment]
On Wed, May 11, 2016 at 10:51 AM, GregorioDiStefano <
notifications@github.com> wrote:

> the .travis.yml update adds the actual checking for dead code
>

Which is fine as it's not removing dead code. Not sure what's your
preferred approach to commits, I usually try to have 1 logical change in a
commit (though not always possible/practical). In this case I'd have 2
commits. First one removing dead code, followed by the second, enabling
travis checks.

If that's not the practice you follow, then it's also fine by me too :)

**Comment by kacf** [comment]
I second @bboozzoo, the dead code removal should in the first commit, and then travis update in second commit (in that order, to avoid breaking the build in between).

**Comment by GregorioDiStefano** [comment]
Thanks guys, that indeed makes sense. Will fix.

Meanwhile, I made a PR to deadcode: since we are using ldlfags to set the buildnumber, deadcode is detecting that variable as unused. I added the ability to ignore a filename:identifier by passing the -ignore flag. 

See here if you have any comments: https://github.com/tsenart/deadcode/pull/4

**Comment by kacf** [comment]
> See here if you have any comments: tsenart/deadcode#4

Nice!

**Comment by GregorioDiStefano** [comment]
can someone take a look at the changes in: https://github.com/GregorioDiStefano/deadcode
Considering that the author isn't interacting with any of the other pull requests, he probably wont look at this one either.

**Comment by kacf** [comment]
It's a shame he doesn't respond.

**Comment by bboozzoo** [comment]
Hmm @GregorioDiStefano are you sure the pull request is openend to the right repository? It seems that the original code comes from here: https://github.com/remyoudompheng/go-misc

**Comment by GregorioDiStefano** [comment]
@bboozzoo Right, but it seems like he's been ignoring pull requests as well.

**Comment by kacf** [comment]
Should you then point Travis to your repository instead, and add the exception for `BuildNumber`?

**Comment by kacf** [comment]
You need to add the exception for `BuildNumber`, otherwise the test fails.

**Comment by bboozzoo** [comment]
On Wed, May 18, 2016 at 1:25 PM, Kristian Amlie <notifications@github.com>
wrote:

> You need to add the exception for BuildNumber, otherwise the test fails.
>

How about we fork deadcode to mendersoftware, push necessary fixed to
master and grab if from there during the build?

-- 
Maciej Borzecki

**Comment by GregorioDiStefano** [comment]
@bboozzoo done

**Pull request merged**
