### PR TITLE
keystore: ed25519 support

### PR DESCRIPTION
**Pull request by mchalski**
quick fix as part of a research task: https://tracker.mender.io/browse/MEN-3737

the client supports RSA and ECC keys out of the box. the only missing curve that may be important in the future is ed25519.

with this minimal fix ed25519 keys work correctly (see jira discussion for details).

tests: https://github.com/mendersoftware/meta-mender/pull/1034

Pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/166729018 

(EDIT: ignore - the meta mender PR was closed after all, it was a miscommunication)

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [ ] Make sure that all commits have a [`Changelog`](../CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [ ] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by mchalski** [comment]
@kacf fixed the changelog.

I'll try adding the test cases.

**Comment by kacf** [comment]
Great, thanks!

**Comment by kacf** [comment]
So as mentioned in the standup, the failure is because we mixed two things. This PR signs the auth request, whereas the [test in meta-mender](https://github.com/mendersoftware/meta-mender/pull/1034) is testing for signing the artifact. Confusing!

So I think the way forward is this:

1. Close https://github.com/mendersoftware/meta-mender/pull/1034. We might use it later, but now is not the time.
2. We don't have a black box test for auth request signing, except for the integration tests, but I think this is a tad too heavyweight. I suggest making a unit test for this in `auth_test.go` instead.

FWIW, I looked into whether we can easily add ED25519 keys to the artifact signing as well, perhaps just a slight tweak of your original change to get both! But this turned out to be a bit more involved, so it's not the low hanging fruit that I hoped.

**Comment by oleorhagen** [comment]
Superseeded  by #582

**Pull request closed without merging**
