### PR TITLE
Bootstrap artifact fixes

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
Looks good.

I would remove both `Changelog` entries because the feature is not released yet (iow such entries give no meaning coming from `3.4.x` versions).

**Comment by kacf** [comment]
Ah good point.

**Comment by kacf** [comment]
@oleorhagen, @lluiscampos: The nasty upgrade bug I was talking about in the last commit!

**Comment by oleorhagen** [comment]
Hah! Good one!

**Comment by kacf** [comment]
Finally https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/683420593 passed. The one failure which is there is some infrastructure error, and happened after all the tests had already passed.

**Pull request merged**
