### PR TITLE
Ensure 128-bit security in client keys like the rest of the system

### PR DESCRIPTION
**Pull request by estenberg**

### CODE REVIEW

**Comment by estenberg** [comment]
@bboozzoo could you have a look, please?

**Comment by bboozzoo** [comment]
@GregorioDiStefano @kacf client PRs don't go through integration tests?

**Comment by kacf** [comment]
Currently not, but it's on its way. I just have to fix the currently broken Yocto build.

But they will not be tested in Travis, no. We can't, because we have to build with Yocto first. So it will be a semi-manual process by me and Greg still.

**Comment by estenberg** [comment]
ping? @bboozzoo you think it's safe to merge so we can test with the round of beta testing coming up?

**Pull request merged**
