### PR TITLE
Upgrade to Go 1.10.3 in Travis tests

### PR DESCRIPTION
**Pull request by mirzak**
To match the current version we are using on release branches.

Changelog: None

Signed-off-by: Mirza Krak <mirza.krak@northern.tech>

### CODE REVIEW

**Comment by mirzak** [comment]
It didn't like that I used the web-editor?

**Comment by kacf** [comment]
Hmm, I guess not. I haven't seen that before. However, I remember an issue that Github seems to use CRLF line endings everywhere. Maybe it's doing so here, and the changelog checker is misunderstanding it.

**Comment by mirzak** [comment]
Will create a new PR

**Comment by mirzak** [comment]
Superseded by #301

**Pull request closed without merging**
