### PR TITLE
Switch IRC link from Freenode to Libera.

### PR DESCRIPTION
**Pull request by kacf**
Changelog: None

Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

### CODE REVIEW

**Comment by kacf** [comment]
I will do the other repos too, but am starting with this one.

**Review by michaelatmender — CHANGES_REQUESTED** [review]
I would suggest using [https://web.libera.chat/?#mender](https://web.libera.chat/?#mender) as the URL

**Comment by kacf** [comment]
> I would suggest using https://web.libera.chat/?#mender as the URL

Good point! I tried to find that link syntax myself, but didn't even think to try the obvious URL. :-)

**Comment by kacf** [comment]
@michaelatmender Updated!

**Review by michaelatmender — APPROVED** [review]

**Pull request merged**
