### PR TITLE
fixed typo

### PR DESCRIPTION
**Pull request by KevinRohn**
Signed-off-by: KevinR <k.rohn@outlook.de>

# External Contributor Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [X] Make sure that all commits have a [`Changelog`](../CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [X] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

fixed typo - ```shcheduled``` should be ```scheduled```.

### CODE REVIEW

**Review by oleorhagen — APPROVED** [review]
Thanks!

The failure is on our end, should be fixed soon, then I will rerun the unit tests and merge :)

**Comment by KevinRohn** [comment]
Thanks :)

**Comment by oleorhagen** [comment]
@KevinRohn If you fetch master and rebase, it should be good now :+1:

**Comment by oleorhagen** [comment]
Rebased on top of master here: #640

**Pull request closed without merging**
