### PR TITLE
Dont Verify SSL if skip verify is set

### PR DESCRIPTION
**Pull request by prashanthjbabu**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits have a [`Changelog`](../CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

If skip verify is set , then we shouldnt call `VerifyResult`

### CODE REVIEW

**Review by kacf — DISMISSED** [review]
You need to provide a commit message. The title of the PR and the description you posted are ideal to use as the commit message. You should keep the `changelog: commit` as well, but don't make it the top line.

**Comment by kacf** [comment]
Code wise it looks ok to me, but maybe @merlin-northern should take a look.

**Comment by oleorhagen** [comment]
What struck me is, why isn't this:
https://github.com/mendersoftware/mender/blob/1352af9955364024588daed853a5aa6141de9e92/client/client.go#L459
enough? :thinking:

**Comment by prashanthjbabu** [comment]
@kacf  I've fixed the commit message .
@oleorhagen I was expecting the same , but it looks like  its the responsibility of the caller to decide whether to call `VerifyResult` or not ?

**Comment by merlin-northern** [comment]
> @kacf I've fixed the commit message .
> @oleorhagen I was expecting the same , but it looks like its the responsibility of the caller to decide whether to call `VerifyResult` or not ?

thanks for the patch.
I am a bit curious and worried, do you have an example certificate that needs this patch?

**Comment by prashanthjbabu** [comment]
Here's one
```
-----BEGIN CERTIFICATE-----
MIIDBjCCAe4CCQCtxYiQ55s7zDANBgkqhkiG9w0BAQsFADBFMQswCQYDVQQGEwJB
VTETMBEGA1UECAwKU29tZS1TdGF0ZTEhMB8GA1UECgwYSW50ZXJuZXQgV2lkZ2l0
cyBQdHkgTHRkMB4XDTE4MDYwNTEwNDkyMFoXDTE5MTAxODEwNDkyMFowRTELMAkG
A1UEBhMCQVUxEzARBgNVBAgMClNvbWUtU3RhdGUxITAfBgNVBAoMGEludGVybmV0
IFdpZGdpdHMgUHR5IEx0ZDCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEB
AOCPIRD87Y/9YoxRNBKFFIuFEmMVuyXTZsWUCXSTTC3YgGePzkM7QSyjpkNxburG
kSQjWQEmPB+r6GkSgE7El38ImGITaj/oKjo6LGM+aadHu2o9B0N5wSpQ3MdFH2Xj
+kenBeWY4fBr+407Y3Nt6NILrQqJ09vFOKkOpSFx0JzIMQ8n3LT4PmHAhlUZoxS2
/sT8he3N84nlFNphpixmPqrbE8pYmQQaMBp7aedHE0yAWMNdD2vRxwG+ENvJQFtb
btJd+KV9MYnUAmh0lJ6CnQxapF5iAjsm17exe/p8w89+XEQX47t77tPy+CGQ+ZGJ
KDmdHAD1kOSAdvDLDuDJax8CAwEAATANBgkqhkiG9w0BAQsFAAOCAQEAl8Sgv4bu
u9ScZSinuIlrtfqqUi3xn8hjfTD9b2GYa73s9jW6ki6XsMCUVtl7tQvx7gbEGbDp
j4sCsrQAPl58qyzaawyiFc+Y1gQjwEIDPilmF8EAzdw5tYr13QDtH7JGe+XWacnS
QFTXpdasTgr5VeaVUWiUF1ovagGqI4cufzPj2MqDN31HYDsmVrqkkNgrCdKFIjQG
nAwPW24lrQRanp0EGLswJGoWxfhibTZl0wrgqbgP5EwoeDpzq5zrfmqYz/eCGdb/
Er5QB8HKzRyLjZGKqv1LYjdyCaIH9n4KozZdWGL7YmnXTRC6szfaoErWHuxD+/Gt
wI8pyO/vb/40eQ==
-----END CERTIFICATE-----
```

**Review by merlin-northern — APPROVED** [review]
thanks for the patch @prashanthjbabu 
@oleorhagen `InsecureSkipHostVerification` does only hosts verification, and it is not an OpenSSL flag.

**Pull request merged**
