### PR TITLE
Update README.md fixed typo from uptdated to updated

### PR DESCRIPTION
**Pull request by Montereytony**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits follow the conventional commit [specification](https://www.github.com/mendersoftware/mendertesting/commitlint/grammar.md) for the Mender project.

The majority of our contributions are fixes, which means your commit should have
the form below:

```
fix: <SHORT DESCRIPTION OF FIX>

<OPTIONAL LONGER DESCRIPTION>

Changelog: <USER-FRIENDLY-CHANGE-DESCRIPTION> or <None>
Ticket: <TICKET NUMBER> or <None>
```

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Review by lluiscampos — CHANGES_REQUESTED** [review]
Hello @Montereytony and thanks for your contribution. Good fix :eyes:

Please check our contributing guidelines above :point_up: I can fix the commit format for you but we need at least for you to sign it.

**Comment by Montereytony** [comment]
Hello Lluis,
Sorry for not following the guidelines.  I created the commit online and do
not know how to sign it. I created a GPG key and uploaded my public key to
Github. Maybe I have to clone the repo, make the change on my laptop and
then commit again. I do not want to create a mess, so I will wait for
your feedback.
Thank you!
--Tony

**Comment by lluiscampos** [comment]
> (...) Maybe I have to clone the repo, make the change on my laptop and then commit again.

Yes, exactly. You need to:
* `git clone` your fork,
* checkout branch `patch-1`,
* do `git commit --amend -s`,
* and finally `git push --force`

See also the explanation [here](https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#sign-your-work).

I am sorry for the trouble for such an small change. But then you know for the next time!

**Comment by Montereytony** [comment]
Hello,

I very much appreciate your patience and your willingness to teach me. I
did:

git clone ***@***.***:Montereytony/mender.git
git checkout branch patch-1 (this did not do anything)
cd mender
vi README.md
git commit --amend -s
git push --force

--Tony

**Comment by lluiscampos** [comment]
> Hello, I very much appreciate your patience and your willingness to teach me. I did: git [...]

Hello again! It didn't work. You can see here in GitHub that the PR did not update (besides your comment).

Right, the checkout has to be done inside the code directory, that is why the command did nothing to you. Please try again:
```git clone ...Montereytony/mender.git
cd mender/
git checkout patch-1
git commit --amend -s
git push --force
```

Once you technically sign the work I will take care of the rest. Thanks again for your patience :smiley:

**Comment by Montereytony** [comment]
Thank you again! I think it worked this time :

***@***.*** ~/Projects/Github/mender % git push --force

Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 12 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 369 bytes | 369.00 KiB/s, done.
Total 3 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
To github.com:Montereytony/mender.git
 + ad8786e2...7068b2f0 patch-1 -> patch-1 (forced update)

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
