### PR TITLE
Followups after #1275.

### PR DESCRIPTION
**Pull request by kacf**
Followups plus the discovery and subsequent removal of Boost::filesystem, since we don't actually need it.

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]
I don't understand the first two commits (I probably missed the background).

The other two look good to me, nice to get the rid of one boos library in favor of the std library.

**Comment by kacf** [comment]
@oleorhagen and I already discussed the revert, so I think I can say that it's approved (basically I made a mistake when removing his earlier code, so I reverted my commit, and then reverted his original introduction of the code instead).

**Review by oleorhagen — APPROVED** [review]
I guess a case could have been made for something like `url::Join` or similar

**Comment by kacf** [comment]
It could. OTOH there is no alternative for URLs like there is for platform paths.

**Comment by oleorhagen** [comment]
> It could. OTOH there is no alternative for URLs like there is for platform paths.

It's usually nice when it's present to handle double `/` etc

**Review by vpodzime — APPROVED** [review]
I'd squash the first two commits. Regarding `join()` and absolute path as the second argument -- it's how Python's `os.path.join()` works as well so I think it's quite a common practice to ignore the first argument in such cases. And :+1: for not using it for URLs, I was actually planning to change that too.

**Comment by kacf** [comment]
> I'd squash the first two commits

Normally I'd do that too, but for reverts I think it's worth keeping them separate for historical reasons (so that they match 1-to-1).

**Comment by kacf** [comment]
> > It could. OTOH there is no alternative for URLs like there is for platform paths.
> 
> It's usually nice when it's present to handle double `/` etc

I'll add this.

I also forgot to move the files to different directories (out of `boost_filesystem`), so I'll do that too.

**Review by vpodzime — APPROVED** [review]
ACK

**Comment by kacf** [comment]
> I guess a case could have been made for something like `url::Join` or similar

Submitted in https://github.com/mendersoftware/mender/pull/1291.

**Pull request merged**
