### PR TITLE
build: automakify the rest of the root Makefile.am

### PR DESCRIPTION
**Pull request by oleorhagen**
This just solves all the DESTDIR, prefix, stuff automatically, and also
symmetrically mirrors it all for install and uninstall.

Just makes life easier.

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Review by lluiscampos — COMMENTED** [review]
If any, this should be part of the `configure.ac`, right? Also see [this note](https://github.com/mendersoftware/mender/pull/1104/files#diff-0462e381b2fb3286568215681c8983490a37ac9ae0f0c5ee304df7fa6426d4afR44) hinting that we will remove all it anyway.

**Comment by oleorhagen** [comment]
> If any, this should be part of the `configure.ac`, right? Also see [this note](https://github.com/mendersoftware/mender/pull/1104/files#diff-0462e381b2fb3286568215681c8983490a37ac9ae0f0c5ee304df7fa6426d4afR44) hinting that we will remove all it anyway.

Yes, you are right. And it will all be removed anyway. But this was the easy approach, and I need it for the Yocto recipes atm, and it is playing a lot nicer with the autotools recipe than our hand-written stuff.

Basically this is a no-op.

**Comment by lluiscampos** [comment]
> > If any, this should be part of the `configure.ac`, right? Also see [this note](https://github.com/mendersoftware/mender/pull/1104/files#diff-0462e381b2fb3286568215681c8983490a37ac9ae0f0c5ee304df7fa6426d4afR44) hinting that we will remove all it anyway.
> 
> Yes, you are right. And it will all be removed anyway. But this was the easy approach, and I need it for the Yocto recipes atm, and it is playing a lot nicer with the autotools recipe than our hand-written stuff.
> 
> Basically this is a no-op.

As long as we keep that note in that we will eventually clean up the file (including the changes from this PR), then I am okey with it :+1:

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
> > > If any, this should be part of the `configure.ac`, right? Also see [this note](https://github.com/mendersoftware/mender/pull/1104/files#diff-0462e381b2fb3286568215681c8983490a37ac9ae0f0c5ee304df7fa6426d4afR44) hinting that we will remove all it anyway.
> > 
> > 
> > Yes, you are right. And it will all be removed anyway. But this was the easy approach, and I need it for the Yocto recipes atm, and it is playing a lot nicer with the autotools recipe than our hand-written stuff.
> > Basically this is a no-op.
> 
> As long as we keep that note in that we will eventually clean up the file (including the changes from this PR), then I am okey with it +1

Yeh, it will happen no matter as soon as we move to CMake

**Comment by oleorhagen** [comment]
No need, that that CMake is just around the corner

**Pull request closed without merging**
