### PR TITLE
Pipeline: update to golang 1.16 and minor clean-ups

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
@kacf @tranchitella please look at the second commit.

**Comment by lluiscampos** [comment]
`godbus` source code: https://github.com/godbus/dbus/blob/e6cb346e4ee46b3c65ab915ceeb0f3739c563c9b/dbus.go#L49

**Comment by lluiscampos** [comment]
@mender-test-bot start pipeline :crossed_fingers:

**Review by tranchitella — APPROVED** [review]

**Review by mzedel — APPROVED** [review]
The pipeline part LGTM - and I'll trust the others for the dbus part 👌

**Pull request merged**
