### PR TITLE
Men 5544 update control map poll interval config

### PR DESCRIPTION
**Pull request by wozniakk**
### Description

This is implementation proposal of task [MEN-5544](https://tracker.mender.io/browse/MEN-5544) that I found marked `helpwanted` in public [issue tracker](https://tracker.mender.io/issues/?filter=11500).

### CODE REVIEW

**Comment by oleorhagen** [comment]
Hello @wozniakk and thank you for your contribution!

Also, I apologize for the delay in the review process, but we have been very busy lately. I will have a look at this first thing in the morning tomorrow :)

**Review by oleorhagen — APPROVED** [review]
Seriously fine work!

Only thing I'm a little unsure of is the last commit, we don't necessarily need to show this in the examples I think, considering `control_maps` are pretty niche, but feel free to change my mind here.

Also, sorry for the delay!

@wozniakk

**Comment by wozniakk** [comment]
Hello @oleorhagen, thank you for the review. First, let me say that nice product you have, greatly prepared for external contributions.

I believe my idea behind adding `UpdateControlMapPollIntervalSeconds` to every place possible, was to avoid new log warnings popping up, but maybe it's not a problem at all. I can easily amend latest commit. Please let me know what you think.

**Comment by oleorhagen** [comment]
> Hello @oleorhagen, thank you for the review. First, let me say that nice product you have, greatly prepared for external contributions.
> 
> I believe my idea behind adding `UpdateControlMapPollIntervalSeconds` to every place possible, was to avoid new log warnings popping up, but maybe it's not a problem at all. I can easily amend latest commit. Please let me know what you think.

I think we should probably remove them from the examples, other than that we're good.

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by wozniakk** [comment]
Example config files are now reverted.

**Comment by oleorhagen** [comment]
> Example config files are now reverted.

Great! Running the full test suite now

**Comment by oleorhagen** [comment]
Everything looks to be alright, however, let's make sure they all pass - rerunning the integration tests.

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Pull request closed without merging**
