### PR TITLE
MEN-4001: switch to the new PUT endpoint to update inventory attributes

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
Depends on https://github.com/mendersoftware/inventory/pull/214

**Comment by tranchitella** [comment]
Manually launched pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/197641614

**Review by kacf — APPROVED** [review]
The license check failed. But I will cherry-pick this change to my PR instead of merging it, since I anyway need to test it together the integration test.

**Comment by tranchitella** [comment]
@kacf good, feel free to close this PR then! 👍

**Comment by kacf** [comment]
Cherry-picked locally, will push soon!

**Pull request closed without merging**
