### PR TITLE
Fixed typo in CLI help message

### PR DESCRIPTION
**Pull request by MaciejTe**
Changelog: None

Signed-off-by: Maciej Tomczuk <maciej.tomczuk@northern.tech>

### CODE REVIEW

**Comment by MaciejTe** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
The commit title is `Changelog: None` :sweat_smile: Can you give it a more meaningful name?

**Comment by MaciejTe** [comment]
@lluiscampos Thanks for noticing that, I misunderstood contribution guide at first glance :-D changed commit message.

**Comment by lluiscampos** [comment]
No need to re-run the pipeline. Nice work @MaciejTe

**Pull request merged**
