### PR TITLE
k8s update module and artifact generator

### PR DESCRIPTION
**Pull request by tranchitella**
k8s update module and artifact generator, compatible with any certified Kubernetes distribution including k3s.io

### CODE REVIEW

**Comment by mirzak** [comment]
Good stuff @tranchitella, though I think this should go in https://github.com/mendersoftware/mender-update-modules

**Comment by tranchitella** [comment]
@mirzak shall I launch a PR for https://github.com/mendersoftware/mender-update-modules, both for the module and the artifact gen, following the convention you use there (folders k8s/{module,module-artifact-gen}?

**Comment by tranchitella** [comment]
Just in case: https://github.com/mendersoftware/mender-update-modules/pull/16

**Comment by mirzak** [comment]
> @mirzak shall I launch a PR for https://github.com/mendersoftware/mender-update-modules, both for the module and the artifact gen, following the convention you use there (folders k8s/{module,module-artifact-gen}?

Yeah, that was my intention. Sorry for not being clear.

The intention of the https://github.com/mendersoftware/mender-update-modules repository is to gather all community maintained modules (and generators) in one place, and I do not think that we plan to add any more modules here (part of Mender client source tree) and only reason I think they are here is because we did not have the other repository when they where created.

**Comment by tranchitella** [comment]
@mirzak got it, closing this PR, then.

**Comment by lluiscampos** [comment]
> [...] and only reason I think they are here is because we did not have the other repository when they where created.

@mirzak You are right. Furthermore, we should revisit this decision: I think we could move the deb/rpm there also, leaving here only the ones we consider "first class citizens" kind of Update Modules. I will take a note for the next client team meeting.

**Pull request closed without merging**
