### PR TITLE
QA-221: Migrate code coverage to coveralls

### PR DESCRIPTION
**Pull request by lluiscampos**

### CODE REVIEW

**Comment by lluiscampos** [comment]
Still missing the acceptance tests part, so stopping the pipeline here.

**Comment by lluiscampos** [comment]
@oleorhagen We have a problem with our design for mender client.

The design idea is to use the parallel feature of coveralls, using as a unique id the Pipeline ID. However this repository triggers builds in two different repos: mender (unit tests) and mender-qa (acceptance tests), so we don't have a single Pipeline ID. Also, the two builds are started completely independent, so we cannot make a unique ID by just concatenating the two, for example.

I don't have a good solution. My only idea is to run the unit tests (also) in mender-qa, but I am hoping for you to have a good suggestion :crossed_fingers:

**Comment by lluiscampos** [comment]
Testing now together with https://github.com/mendersoftware/mender-qa/pull/423 @ [Pipeline 194060506](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194060506)

**Comment by lluiscampos** [comment]
The design has been changed to use Git sha as "build id" in the Coveralls API.

Testing now together with https://github.com/mendersoftware/mender-qa/pull/423 @ [Pipeline 194061540](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194061540)

**Comment by lluiscampos** [comment]
@oleorhagen Just to be explicit: this and https://github.com/mendersoftware/mender-qa/pull/423 are both ready for review.

**Comment by lluiscampos** [comment]
> Testing now together with [mendersoftware/mender-qa#423](https://github.com/mendersoftware/mender-qa/pull/423) @ [Pipeline 194061540](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194061540)

New build @ [Pipeline 194180788](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194180788)

**Comment by lluiscampos** [comment]
> > Testing now together with [mendersoftware/mender-qa#423](https://github.com/mendersoftware/mender-qa/pull/423) @ [Pipeline 194061540](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194061540)
> 
> New build @ [Pipeline 194180788](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194180788)

New build @ [Pipeline 194367085](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/194367085)

**Review by oleorhagen — APPROVED** [review]

**Comment by lluiscampos** [comment]
It works :tada: 

The acceptance-XXX checks did not arrive to GitHub, but the final check (after the parallel build is closed) did arrived and reported the correct coverage. I suspect that these acceptance-XXX will start working once we have some build from master.

Merging!

**Comment by oleorhagen** [comment]
Hell yeah! Thank you for your patience on this! It is appreciated.

**Pull request merged**
