### PR TITLE
MEN-4179: fix, support white spaces in single-file artifacts' names

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: title

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>
(cherry picked from commit 80af399cb7c967a8a9c5fb4388ba77f4437fc461)

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by kacf — APPROVED** [review]

**Comment by kacf** [comment]
I think the error is spurious, but not completely sure. I took the liberty of retrying, hopefully saving you some time before arriving at work. :-)

**Comment by oleorhagen** [comment]
@kacf looks good to me now, can you merge? :pray:

**Comment by kacf** [comment]
Ah, yes, this is what I was talking about earlier, that PR coverage publish stages don't work. I think it's because we have changed the way we do coveralls since 2.3.x. Definitely not important for the release though. Merging!

**Pull request merged**
