### PR TITLE
Adding download and apply commands

### PR DESCRIPTION
**Pull request by mullerch**
Changelog : Adding download and apply commands

Signed-off-by: Christian Müller <christian.muller@wifx.net>

### CODE REVIEW

**Comment by mullerch** [comment]
See [MEN-2932]

**Comment by oleorhagen** [comment]
Hi @mullerch, and thank you for your contribution :)

First off, the gitlab pipeline is red, because you don't have a `Changelog` tag in your commit body. But nevermind for now, there are a lot things to discuss surrounding this PR first ;)

I have to say, I like this idea.

@kacf what is your take on allowing this, as compared to a blocking state-script?

**Comment by oleorhagen** [comment]
Also, @mullerch could you have this PR target the `master` branch instead of `2.2.x` ?

**Comment by mullerch** [comment]
See https://github.com/mendersoftware/mender/pull/515

**Pull request closed without merging**
