### PR TITLE
Some small fixes for dbus.

### PR DESCRIPTION
**Pull request by kacf**
```
commit f8a47b301201916389db5d7191a76531dbfc3ed0
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Thu Oct 22 15:11:34 2020

    Fix incorrect build tag, nolibgio should be nodbus.
    
    Changelog: None
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

commit b93297cde3a288afce6617a81b9db348db94bcd3
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Thu Oct 22 14:37:32 2020

    Make sure dbus is linked to if nodbus tag is off.
    
    Changelog: None
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
```

### CODE REVIEW

**Review by lluiscampos — APPROVED** [review]

**Comment by lluiscampos** [comment]
We are missing [libglib2.0-dev](https://github.com/mendersoftware/mender/blob/feature-client_auth_api/README.md#requirements) at integration pipeline, but I was not expecting it to fail in `build_servers`... why is this job building the client?

**Comment by kacf** [comment]
> We are missing [libglib2.0-dev](https://github.com/mendersoftware/mender/blob/feature-client_auth_api/README.md#requirements) at integration pipeline, but I was not expecting it to fail in `build_servers`... why is this job building the client?

This is not the QEMU client image, it's the Docker client image. I think this goes all the way back to Jenkins actually. Strictly speaking it is wrong to build it in this job, but this part is quite entangled, so I think I prefer not to rock the boat. It has not caused any issues so far.

As far as the failure is concerned, it is a missing dependency in the Docker file. This should be easy to fix.

**Comment by lluiscampos** [comment]
> This is not the QEMU client image, it's the Docker client image. (...)

Ah, of course. Thanks.

**Comment by kacf** [comment]
@lluiscampos: Do you agree with the very last commit? I can't think of any bad effects it would have.

**Comment by lluiscampos** [comment]
> @lluiscampos: Do you agree with the very last commit? I can't think of any bad effects it would have.

Yes, I also think it should be fine.

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
