### PR TITLE
MEN-4295: don't build dbus-related test files when "nodbus" tag is used

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by tranchitella** [comment]
Depends on: https://github.com/mendersoftware/meta-mender/pull/1257

**Comment by tranchitella** [comment]
Manual QA pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/237391673

**Review by kacf — APPROVED** [review]

**Review by lluiscampos — CHANGES_REQUESTED** [review]
This doesn't work locally for me, I still have the same error. Have you tried it locally? Keep in mind that this fix is non-testable in CI, as `meta-mender-ci` disables ptest.

**Comment by lluiscampos** [comment]
> This doesn't work locally for me, I still have the same error. Have you tried it locally? Keep in mind that this fix is non-testable in CI, as `meta-mender-ci` disables ptest.

I looked a bit more into it. This is the patch that we need in `meta-mender`:

```
$ git diff
diff --git a/meta-mender-core/recipes-mender/mender-client/mender-client.inc b/meta-mender-core/recipes-mender/mender-client/mender-client.inc
index e1382bdc..6ecc3282 100644
--- a/meta-mender-core/recipes-mender/mender-client/mender-client.inc
+++ b/meta-mender-core/recipes-mender/mender-client/mender-client.inc
@@ -110,6 +110,7 @@ PACKAGECONFIG_append = " split-mender-config"
 
 _MENDER_TAGS = "${@bb.utils.contains('PACKAGECONFIG', 'dbus', '', 'nodbus', d)}"
 EXTRA_OEMAKE_append = " TAGS='${_MENDER_TAGS}'"
+GOPTESTBUILDFLAGS_append = " -tags '${_MENDER_TAGS}'"
 
 do_compile() {
     GOPATH="${B}:${S}"
```

See [poky source code](https://git.yoctoproject.org/cgit/cgit.cgi/poky/tree/meta/classes/go-ptest.bbclass#n8).

**Comment by tranchitella** [comment]
@lluiscampos done, new combined pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/237471734

**Review by lluiscampos — APPROVED** [review]

**Pull request merged**
