### PR TITLE
Merge with master, plus one more fix

### PR DESCRIPTION
**Pull request by kacf**
```
commit fc72714ce118c494af219c3d032939b574be6f33
Merge: 2b4741ef 405cac1f
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Fri Feb 10 11:43:38 2023

    Merge branch 'master' of github.com:mendersoftware/mender into feature-c++-client
    
    All Go related files were deleted.
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>

commit 60c7858e8c6e0e71813329ccdb7ff5f2f858d5d8
Author: Kristian Amlie <kristian.amlie@northern.tech>
Date:   Fri Feb 10 11:48:09 2023

    ci: Add correct worker tag, like in master branch.
    
    Signed-off-by: Kristian Amlie <kristian.amlie@northern.tech>
```

### CODE REVIEW

**Comment by kacf** [comment]
The changelog will require manual intervention when we release, so it doesn't matter much what it says I think.

**Comment by kacf** [comment]
Only the very last commit is new, but the content is the same as in master (we just missed something earlier).

**Review by oleorhagen — APPROVED** [review]

**Comment by oleorhagen** [comment]
Thanks!

Why is coverage down? :thinking:

**Comment by kacf** [comment]
> Thanks!
> 
> Why is coverage down? thinking

I have no idea, I looked at it and their data makes no sense. Just coveralls being its usual confusing self.

**Comment by oleorhagen** [comment]
> > Thanks!
> > Why is coverage down? thinking
> 
> I have no idea, I looked at it and their data makes no sense. Just coveralls being its usual confusing self.

It might be a lot cheaper... But it's also a lot _shittier_...

**Pull request merged**
