### PR TITLE
Ignore me

### PR DESCRIPTION
**Pull request by oleorhagen**
# External Contributor Checklist

🚨 Please review the [guidelines for contributing](../CONTRIBUTING.md) to this repository.

- [x] Make sure that all commits have a [`Changelog`](../CONTRIBUTING.md#changelog-tags) tag. If nothing should be added to the Changelog, add a `Changelog: None` tag. If there is a change, add `Changelog: Commit`, or `Changelog: Title`, depending on what should be included in the changelog.

- [x] Make sure that all commits are signed with [`git --signoff`](https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work). Also note that the signoff author must match the author of the commit.

### Description

Please describe your pull request.

Thank you!

### CODE REVIEW

**Comment by oleorhagen** [comment]
@lluiscampos I think this is what we actually want.
1. This will bring coverage back up to where it really is (about 70%)
2. If you look closer at the codecov commits, it seems to me that the two last ones resulted in the exact same results, so I guess the last commit is not really needed.

If you agree, I will squash this, and remove the last commit, and then close all the other PRs.

**Comment by oleorhagen** [comment]
The #549 will be the official follow up of this one.

**Comment by lluiscampos** [comment]
>     2. If you look closer at the codecov commits, it seems to me that the two last ones resulted in the exact same results, so I guess the last commit is not really needed.
> 

Yes, I don't think it should be required, I understand that a report will be generated with the first tag, then just amended when the second part is available.

> 
> If you agree, I will squash this, and remove the last commit, and then close all the other PRs.

:+1:

**Comment by oleorhagen** [comment]
Followd up in #549

**Pull request closed without merging**
