### PR TITLE
Port to new and smaller cli package

### PR DESCRIPTION
**Pull request by alfrunes**
Request for comment: what do you think?
The binary size is reduced significantly as this cli package only depends on built-in golang packages (in addition to the unix/windows packages in the golang `x` repository).

### CODE REVIEW

**Comment by alfrunes** [comment]
This PR is branched on top of #489, only the last three commits provide changes.

**Comment by oleorhagen** [comment]
I think this should be discussed in the ticket: https://tracker.mender.io/browse/MEN-3065 if this is really what we want to do.

And if we go with this? Maybe it should be a library of it's own, and standardized across all our CLI's?

**Comment by oleorhagen** [comment]
Quickly had a look over the cli lib though, and I think it looks nice! Kudos!

**Comment by kacf** [comment]
I will look more at this once we have the base snapshot feature merged.

**Comment by alfrunes** [comment]
@kacf ?

**Comment by kacf** [comment]
Oops, sorry, I didn't mean to close this. It was in my list of tabs "related to" the snapshot feature and I closed it by mistake!

**Comment by kacf** [comment]
Wait, that's not what happened. It was auto-closed because I deleted the feature branch! You need to reopen it against the master branch now that we merged the main feature. :-)

**Pull request closed without merging**
