### PR TITLE
Bump: mendersoftware/openssl to version v1.1.0

### PR DESCRIPTION
**Pull request by merlin-northern**
ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Review by oleorhagen — COMMENTED** [review]
Please add a `Changelog` for this @merlin-northern

**Comment by merlin-northern** [comment]
> Please add a `Changelog` for this @merlin-northern

right will do!

**Comment by lluiscampos** [comment]
> > Please add a `Changelog` for this @merlin-northern
> 
> right will do!

I would have waited for dependabot to do this PR, so that we have the same changelog as for every other dependency update (plus less work for you).

**Comment by merlin-northern** [comment]
> > > Please add a `Changelog` for this @merlin-northern
> > 
> > 
> > right will do!
> 
> I would have waited for dependabot to do this PR, so that we have the same changelog as for every other dependency update (plus less work for you).

even better!

**Comment by merlin-northern** [comment]
> > > > Please add a `Changelog` for this @merlin-northern
> > > 
> > > 
> > > right will do!
> > 
> > 
> > I would have waited for dependabot to do this PR, so that we have the same changelog as for every other dependency update (plus less work for you).
> 
> even better!

superseded by [mender/pull/670](https://github.com/mendersoftware/mender/pull/670)

**Pull request closed without merging**
