### PR TITLE
Revert "Make command output less ugly in the log."

### PR DESCRIPTION
**Pull request by oleorhagen**
This reverts commit 8c672c35290a1dae9021a29264365ddb39a0300f.

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by kacf — APPROVED** [review]
What shall we do with the ticket? Reject it as "too difficult, not worth it", or keep it open?

**Comment by kacf** [comment]
I'm leaning towards the former, and just say this is good enough.

**Comment by oleorhagen** [comment]
@kacf we have created a follow up ticket, see https://tracker.mender.io/browse/MEN-5088

**Pull request merged**
