### PR TITLE
Inf 306 readme license

### PR DESCRIPTION
**Pull request by ThomasRyd**
michaelatmender should upload Mender logo <mender_logo.png> found in README.md before merging.

### CODE REVIEW

**Comment by kacf** [comment]
A couple of issues:

* It is common practice to wrap text files at 80 characters, since they are often read using terminal tools.
* Don't switch the mode of `README.md` to become executable (`0644 -> 0755`).
* The license check currently fails because it expects the old short format of the Apache license. I think you can leave the license part out of this pull request for now, since I'm anyway in the process of cleaning this up everywhere starting with https://github.com/mendersoftware/mendertesting/pull/5 (more PRs will follow).

Let me know if you agree, it's quick for me to fix the issues before merging.

**Comment by kacf** [comment]
Oh, and Thomas, I'm disappointed, you need to sign-off the commits! :-)

**Comment by kacf** [comment]
@michaelatmender: see descr

**Comment by ThomasRyd** [comment]
Of course

**Comment by kacf** [comment]
Superseded by https://github.com/mendersoftware/mender/pull/57.

**Pull request closed without merging**
