### PR TITLE
fix: the HTTP proxy must bind on localhost, not on all the interfaces

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: Title
Ticket: MEN-5642

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by tranchitella** [comment]
@mender-test-bot start --pr integration/2039

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr integration/2039

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr integration/2039

**Comment by tranchitella** [comment]
Integration tests depend on https://github.com/mendersoftware/integration/pull/2039.

The following failures are unrelated to this PR:
- tests/test_basic_integration.py::TestBasicIntegrationEnterprise::test_double_update_rofs
- tests/test_basic_integration.py::TestBasicIntegrationEnterprise::test_update_no_compression
- tests/test_basic_integration.py::TestBasicIntegrationOpenSource::test_double_update_rofs
- tests/test_basic_integration.py::TestBasicIntegrationOpenSource::test_update_no_compression

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr integration/2039

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr integration/2039

**Comment by oleorhagen** [comment]
Pipeline: https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/552098697

**Comment by oleorhagen** [comment]
@mender-test-bot cherry-pick to: `3.0.x`

**Comment by oleorhagen** [comment]
@mender-test-bot cherry-pick to: `3.3.x`

**Pull request merged**
