### PR TITLE
Move cross compilation to official docs.

### PR DESCRIPTION
**Pull request by estenberg**

### CODE REVIEW

**Comment by estenberg** [comment]
Adding to docs here: https://github.com/mendersoftware/mender-docs/pull/525

**Comment by mirzak** [comment]
The mender-docs PR has been merged, merge this one as well? @estenberg @kacf

**Comment by estenberg** [comment]
Yeah, just not sure about the build failures.. but must be unrelated?

**Comment by kacf** [comment]
Yes, unrelated.

**Pull request merged**
