### PR TITLE
Add demo module for ipk package updates

### PR DESCRIPTION
**Pull request by drewmoseley**
Changelog: Title

Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by mirzak** [comment]
I believe that we should add this to,

      https://github.com/mendersoftware/mender-update-modules

**Comment by lluiscampos** [comment]
> I believe that we should add this to,
> 
> ```
>   https://github.com/mendersoftware/mender-update-modules
> ```

I agree. We should add it in the other repo so that we get more traction there and other users decide to share their modules.

**Comment by drewmoseley** [comment]
Is there a Yocto recipe for that repo?

**Comment by mirzak** [comment]
Not a generic recipe that will install all the modules, but there is a place to put recipes.

https://github.com/mendersoftware/meta-mender-community/tree/sumo/meta-mender-update-modules

**Pull request closed without merging**
