### PR TITLE
MEN-7345: Remove application watchdog support for the systemd service

### PR DESCRIPTION
**Pull request by lluiscampos**
The feature was not part of the first release of the C++ client, and it
has been internally reported to be very noisy for its low value. Remove
it before it hits the next release train.

This reverts commit https://github.com/mendersoftware/mender/commit/d8bb93c6784af9b424428d6c7355ceb16cb132d9.

### CODE REVIEW

**Comment by lluiscampos** [comment]
The test needed to be removed too. See:
* https://github.com/mendersoftware/meta-mender/pull/2172

**Comment by lluiscampos** [comment]
Build for `qemux86_64:uefi_grub:cross-platform` @ [Pipeline 1476481203](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1476481203)

**Review by danielskinstad — APPROVED** [review]

**Review by merlin-northern — APPROVED** [review]
do we have a ticket for it? if we do: -> Ticket:

**Comment by lluiscampos** [comment]
> do we have a ticket for it? if we do: -> Ticket:

I don't understand, do you mean a `Ticket` entry in the git commit body? It [is there](https://github.com/mendersoftware/mender/pull/1668/commits/a3862a6d8647e449ee8bcab478a2ec8685edde57). Or do you mean something else?

**Comment by merlin-northern** [comment]
> > do we have a ticket for it? if we do: -> Ticket:
> 
> I don't understand, do you mean a `Ticket` entry in the git commit body? It [is there](https://github.com/mendersoftware/mender/pull/1668/commits/a3862a6d8647e449ee8bcab478a2ec8685edde57). Or do you mean something else?

oh, sorry, the github description fooled me. sorry for the noise.

**Comment by kacf** [comment]
👍

**Pull request merged**
