### PR TITLE
 MEN-1726: FIXED: Deployment logging is now written syncronously to persistent storage

### PR DESCRIPTION
**Pull request by alfrunes**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Maybe we should get this thing finished?

**Comment by kacf** [comment]
Indeed we should! I'll take this and test it as soon as our test farm is back up.

**Comment by kacf** [comment]
@alfrunes: A heads up: Github doesn't tell me when you push a new version, so ping me with a comment when you've updated something and are waiting for me!

**Comment by alfrunes** [comment]
@kacf now we're in business! :)

**Comment by kacf** [comment]
Alright, thanks! I've started a Jenkins build.

**Comment by kacf** [comment]
Superseded by #284.

**Pull request closed without merging**
