### PR TITLE
Fix several race conditions in Dbus Go routines.

### PR DESCRIPTION
**Pull request by kacf**

### CODE REVIEW

**Comment by kacf** [comment]
@merlin-northern: Do you have a chance to try this out and see if solves the problem you had with mender-connect and token signals when restarting the Mender client?

**Comment by merlin-northern** [comment]
> @merlin-northern: Do you have a chance to try this out and see if solves the problem you had with mender-connect and token signals when restarting the Mender client?

thanks for the ping. I will try and report here. (although later in the afternoon)

**Review by lluiscampos — APPROVED** [review]
Good finds

**Review by tranchitella — APPROVED** [review]

**Comment by kacf** [comment]
Failures are due to an unrelated test problem. This passed on the platforms where it was able to run. Merging, since I have a followup PR which will re-check on all platforms anyway.

**Pull request merged**
