### PR TITLE
Add Community Code of Conduct

### PR DESCRIPTION
**Pull request by michaelatmender**
Changelog: Title

Signed-off-by: Michael Clelland <michael.clelland@mender.io>

### CODE REVIEW

**Comment by mirzak** [comment]
Why so many deviations from the original?

**Comment by michaelatmender** [comment]
> Why so many deviations from the original?

I just followed a suggestion in the JIRA ticket to reuse like this. Here's the [link and discussion](https://tracker.mender.io/browse/MEN-2117?focusedCommentId=91365&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-91365)

**Comment by mirzak** [comment]
Missed that discussion, nevermind that remark. 

We should add links from README.md to CoC. And probably it should be mentioned in the contribution.md as well. What do you think?

**Comment by estenberg** [comment]
I would just drop the section from README.md, as it links to contributing.md which links to code of contduct. This should be enough IMHO.

The main issue is that there is not just one README.md, but each repo has one, and we should try to keep them consistent to avoid user confusion.

@mirzak WDYT?

**Comment by mirzak** [comment]
Sounds reasonable to me

**Pull request merged**
