### PR TITLE
inventory geo script: switch to ipapi.co

### PR DESCRIPTION
**Pull request by merlin-northern**
includes https://github.com/mendersoftware/mender/pull/647

ChangeLog:none
Signed-off-by: Peter Grzybowski <peter@northern.tech>

### CODE REVIEW

**Review by drewmoseley — APPROVED** [review]
LGTM

**Comment by merlin-northern** [comment]
do not merge before https://tracker.mender.io/browse/MEN-4099 is done.

**Comment by oleorhagen** [comment]
I don't know much about this service compared to another, I know @alfrunes mentioned something about some other service he preferred on Slack.

Anywho, for starters, if we merge this, a `Changelog` tag is in order I think.

**Review by kacf — CHANGES_REQUESTED** [review]
I think this should have a changelog. It may affect firewall rules on devices, and fixes a bug that has been reported by customers.

**Comment by oleorhagen** [comment]
@merlin-northern close?

**Comment by oleorhagen** [comment]
No need to keep this open anylonger. If the issue pops back up, we will just re-open this at a later time.

**Pull request closed without merging**
