### PR TITLE
MEN-5096: Refresh update control maps before failing an update

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: Fix the issue in where if a state - say Download - took longer than
the expiration time for the enabled update control map. Then by the time the
client would check its control maps, the map would be expired, and the update
fail. Now the client refreshes the update maps from the server before each
pause, and hence, this issue will be avoided.
Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline --pr integration/1805

**Review by lluiscampos — APPROVED** [review]
I can't believe the fix is so simple :) The test says it all. Good work

Nitpick, the fist sentence sounds incomplete:
```
Changelog: Fix the issue in where if a state - say Download - took longer than
the expiration time for the enabled update control map. Then by the time 
(...)
```

if a state took longer than blablablah, then by the time ...

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline --pr integration/1805

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline --pr integration/1805

**Review by lluiscampos — APPROVED** [review]

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline --pr integration/1805

**Comment by oleorhagen** [comment]
@mender-test-bot --pr integration/1805 --pr meta-mender/1546

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline --pr integration/1805 --pr meta-mender/1546

**Comment by oleorhagen** [comment]
@mender-test-bot cherry-pick to:
* 3.1.x
* 3.0.x

**Pull request merged**
