### PR TITLE
Fix: linting error

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: none

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>

### CODE REVIEW

**Review by oleorhagen — APPROVED** [review]
Thanks!

**Comment by tranchitella** [comment]
@mender-test-bot start pipeline --pr meta-mender/1560

**Comment by kacf** [comment]
I'm not sure why these errors happen, but I'm looking into it, and I've also cherry-picked this change to #917.

**Comment by kacf** [comment]
I'm merging this, I'm quite certain your change is not related, and it brings it closer to passing again.

**Pull request merged**
