### PR TITLE
chore: replace the deprecated `os.SEEK_END` with `io.SeekEnd`

### PR DESCRIPTION
**Pull request by tranchitella**
Changelog: None
Ticket: None

### CODE REVIEW

**Review by kacf — APPROVED** [review]
@lluiscampos, @oleorhagen: I guess this needs to be cherry-picked to the mender-setup repo?

**Comment by lluiscampos** [comment]
@kacf Done last week:
* https://github.com/mendersoftware/mender-setup/pull/10

**Comment by tranchitella** [comment]
Superseded by https://github.com/mendersoftware/mender/pull/1482

**Comment by lluiscampos** [comment]
Thanks @tranchitella :rocket:  But we already had this one:
* https://github.com/mendersoftware/mender/pull/1482

**Pull request closed without merging**
