### PR TITLE
fix(mender-artifact): bump mender-artifact to the latest master

### PR DESCRIPTION
**Pull request by oleorhagen**
Changelog: Title
Ticket: None

Signed-off-by: Ole Petter <ole.orhagen@northern.tech>

### CODE REVIEW

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Review by kacf — APPROVED** [review]

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by oleorhagen** [comment]
@mender-test-bot start pipeline

**Comment by lluiscampos** [comment]
I have done this as part of my work for bootstrap Artifact. Let's close this one as I will be submitting my PR soon.

**Pull request closed without merging**
