### PR TITLE
fix(cmake): Avoid inheriting conflicting flags from static libs.

### PR DESCRIPTION
**Pull request by kacf**
Because flags are inherited from other libraries when you link to them, this does not work well for conflicting flags. Instead, introduce a default for all components, and then override using `target_compile_options`, which always puts the flags last.

Changelog: None
Ticket: None

### CODE REVIEW

**Comment by kacf** [comment]
Hah! This even caught some [things we had missed](https://gitlab.com/Northern.tech/Mender/mender/-/jobs/3864316531) because the flags weren't getting set correctly. Instant value.

**Comment by vpodzime** [comment]
> Hah! This even caught some [things we had missed](https://gitlab.com/Northern.tech/Mender/mender/-/jobs/3864316531) because the flags weren't getting set correctly. Instant value.

Mystery solved for why those things haven't being showing up in CI and our local builds.

**Review by vpodzime — APPROVED** [review]
ACK

**Review by oleorhagen — APPROVED** [review]
Nice!

**Pull request merged**
