### PR TITLE
Fixes UBI device size calculation

### PR DESCRIPTION
**Pull request by samvrlewis**
The code in `getUbiDeviceSize` looks at the `data_bytes` property of the UBI device/volume instead of looking at the total size of the volume. This causes the size of a UBI device to always get undereported and in some cases, such as a failed update, could cause devices to no longer be able to get updated.

To demonstrate this, note that `Data bytes` is 2MB (after a 2MB file is written to the volume) despite the total usable size being 50MB. 

    root@unknown:~# dd if=/dev/urandom of=/tmp/blah bs=1M count=2
    2+0 records in
    2+0 records out
    root@unknown:~# ubiupdatevol /dev/ubi0_0 /tmp/blah
    root@unknown:~# ubinfo /dev/ubi0_0
    Volume ID:   0 (on ubi0)
    Type:        static
    Alignment:   1
    Size:        802 LEBs (52457216 bytes, 50.0 MiB)
    Data bytes:  2097152 bytes (2.0 MiB)
    State:       OK
    Name:        rootfsa
    Character device major/minor: 244:1

Then, trying to update `ubi0_0` with a ~29MB update using Mender:

    root@unknown:/data# mender -debug -rootfs /mnt/attempt-tuesday29/5/BBBB.mender -f
    INFO[0000] Configuration file does not exist: /var/lib/mender/mender.conf  module=config
    DEBU[0000] Reading Mender configuration from file /etc/mender/mender.conf  module=config
    INFO[0000] Loaded configuration file: /etc/mender/mender.conf  module=config
    DEBU[0000] Merged configuration = main.menderConfig{ClientProtocol:"", ArtifactVerifyKey:"", HttpsClient:struct { Certificate string; Key string; SkipVg
    WARN[0000] Could not resolve path link: ubi0_0 Attempting to continue  module=partitions
    WARN[0000] Could not resolve path link: ubi0_1 Attempting to continue  module=partitions
    DEBU[0000] Have U-Boot variable: mender_check_saveenv_canary=1  module=bootenv
    DEBU[0000] List of U-Boot variables:map[mender_check_saveenv_canary:1]  module=bootenv
    DEBU[0000] Have U-Boot variable: mender_saveenv_canary=1  module=bootenv
    DEBU[0000] List of U-Boot variables:map[mender_saveenv_canary:1]  module=bootenv
    DEBU[0000] Have U-Boot variable: mender_boot_part=1      module=bootenv
    DEBU[0000] List of U-Boot variables:map[mender_boot_part:1]  module=bootenv
    DEBU[0000] Setting active partition from configuration and environment: ubi0_1  module=partitions
    INFO[0000] Mender running on partition: ubi0_1           module=main
    DEBU[0000] Read data from device manifest file: device_type=xys-mb-7030-1.1  module=mender
    DEBU[0000] Found needed line: device_type=xys-mb-7030-1.1  module=mender
    DEBU[0000] Current manifest data: xys-mb-7030-1.1        module=mender
    DEBU[0000] Starting device update.                       module=rootfs
    INFO[0000] Start updating from local image file: [BBBB.mender]  module=rootfs
    DEBU[0000] Fetching update from file results: [&{0x1076d470}], 29070848, <nil>  module=rootfs
    Installing update from the artifact of size 29070848
    INFO[0000] no public key was provided for authenticating the artifact  module=installer
    DEBU[0000] checking if device [xys-mb-7030-1.1] is on compatibile device list: [xys-mb-7030-1.1]
    module=installer
    DEBU[0000] installer: processing script: ArtifactInstall_Enter_00  module=installer
    DEBU[0000] installing update xys7030-v18_xysupervisor_updates-feature_squashfs_ubi_2f49889-local-xys-mb-7030-1.1.xyfitimage of size 29093140  module=inr
    DEBU[0000] Trying to install update of size: 29093140    module=device
    DEBU[0000] Active partition: ubi0_1                      module=partitions
    WARN[0000] Could not resolve path link: ubi0_1 Attempting to continue  module=partitions
    WARN[0000] Could not resolve path link: ubi0_1 Attempting to continue  module=partitions
    DEBU[0000] Detected inactive partition ubi0_0, based on active partition ubi0_1  module=partitions
    ERRO[0000] update (29093140 bytes) is larger than the size of device /dev/ubi0_0 (2097152 bytes)  module=device
    ERRO[0000] update image installation failed: no space left on device  module=installer
    ERRO[0000] Installation failed: installer: failed to read and install update: update: can not install update: &{xys7030-v18_xysupervisor_updates-featurs
    ERRO[0000] installer: failed to read and install update: update: can not install update:

The critical line is `ERRO[0000] update (29093140 bytes) is larger than the size of device /dev/ubi0_0 (2097152 bytes)  module=device`.

I think this is a fairly critical issue as it effectively means that:

- You are never able to install an artifact that is bigger than your current artifact
- If an update is interrupted and the UBI volume shows as 'corrupted', the `Data Bytes` will read as 0 bytes which effectively stops ANY update being applied.

I've tested the attached change set on my device and it seems like it rectifies the problem. However, please let me know if there's any edge cases I'm missing or if I've forgotten anything.

I'm using 1.7.0 so have only tested on that release, but (if I'm correct in that this fix is valid) believe it should apply to all releases. Please let me know if I should target a different branch to achieve this.

### CODE REVIEW

**Comment by oleorhagen** [comment]
Hi, @samvrlewis, I will leave this to @kacf. However, this beatutiful description could even be part of the commit. Also, remember the changelog tag. The analysis of the contribution itself, @kacf will take care of :)

**Comment by samvrlewis** [comment]
Thanks for the feedback! I've:

- Added a changelog tag
- Added some of the PR description to the commit message
- Retargeted the PR to master
- Fixed my bad golang formatting!

Patching my local version of 1.7.0 myself until I upgrade sounds OK to me as well.

**Comment by kacf** [comment]
The failure is a known spurious failure, not related, so I'm merging this.

**Comment by kacf** [comment]
Cherry-picked and pushed to 2.1.x as well.

**Pull request merged**
