### PR TITLE
Proper cleanup of HTTP leftovers

### PR DESCRIPTION
**Pull request by vpodzime**

### CODE REVIEW

**Comment by vpodzime** [comment]
@lluiscampos please start an appropriate pipeline here to check it doesn't break anything, at least. To verify it actually fixes something we'll need some new test(s).

**Review by lluiscampos — APPROVED** [review]
The two fixes look good to me. Excellent work.

On the first commit, I would extend the changelog entry to include the actual error log printed by the client. So append something like: "... Fixes `bad_version` error."

> @lluiscampos please start an appropriate pipeline here to check it doesn't break anything, at least. To verify it actually fixes something we'll need some new test(s).

This needs to wait. For unrelated reasons the pipeline is not working ATM

**Comment by lluiscampos** [comment]
It seems to behave now... @mender-test-bot start pipeline :crossed_fingers:

**Comment by vpodzime** [comment]
> So append something like: "... Fixes `bad_version` error."

Done.

**Comment by lluiscampos** [comment]
@vpodzime Rebase on top of latest master to get the CI fixes :+1:

**Review by jo-lund — APPROVED** [review]

**Comment by vpodzime** [comment]
> @vpodzime Rebase on top of latest master to get the CI fixes 👍

Done.

**Comment by lluiscampos** [comment]
The [previous pipeline](https://gitlab.com/Northern.tech/Mender/mender-qa/-/pipelines/1583452424) was :green_circle: - and since then the rebase updates did not bring software changes. Merging.

**Comment by lluiscampos** [comment]
@mender-test-bot cherry-pick to:
* 4.0.x

**Pull request merged**
