### PR TITLE
mender-device-identity: Skip private MAC addresses

### PR DESCRIPTION
**Pull request by nandra**
Signed-off-by: Marek Belisko <marek.belisko@open-nandra.com>

### CODE REVIEW

**Comment by kacf** [comment]
I think we need a bit more background here. I get that the addresses are private, but why shouldn't they be used?

And even if we should avoid them, I'm not sure if we can. Due to the changing identity, this could orphan existing devices on a massive scale.

**Comment by nandra** [comment]
We have specific situation where we use multiple network cards and for some of them MAC is not available so we set same for all of them. In this case without patch devices will be shows with same MAC address.  So with patch we try to avoid that and in real scenario usually adapters have specified MAC address which is not private.

**Comment by kacf** [comment]
Ok. I think this is still fairly specific to your use case. For some people the private address might be all they have, so it's better to rely on the `ifindex` to select the preferred one if there are multiple cards. IMHO, it is too risky to apply this change to everyone, so you should probably keep this in a fork.

**Comment by nandra** [comment]
OK then can be closed. Thanks for comments.

**Pull request closed without merging**
